field.field_settings.yearonly:
  type: mapping
  label: 'Yearonly Settings'
  mapping:
    yearonly_from:
      type: list_integer
      label: 'Yearonly Start year'
    yearonly_to:
      type: list_integer
      label: 'Yearonly last year'

field.value.yearonly:
  type: mapping
  label: 'Default value'
  mapping:
    default_type:
      type: string
      label: 'Default year type'
    default_relative:
      type: string
      label: 'Relative default year'
    default_specific:
      type: string
      label: 'Specific default year'
