_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: cc41562e-d314-40f5-a5b9-15de73703426
name: 'Forest Management Information System'
mail: developmenticon@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
