cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://dev-nfafmis.pantheonsite.io/themes/nfa/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  nfa: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
breadcrumb_home: 1
table: ''
